#!/usr/bin/env bash
# gitui — git GUI comfort in terminal
#
# Template 1 (scripted fake). We show the core proposition in one loop:
# status + staged files + commit box + context key hints.

pause() { sleep "${1:-0.8}"; }
beat()  { sleep "${1:-0.3}"; }

type_line() {
  local s="$1" i
  for (( i=0; i<${#s}; i++ )); do
    printf '%s' "${s:$i:1}"
    sleep 0.03
  done
  printf '\n'
}

prompt() { printf '\033[2m$\033[0m '; }

clear
pause 0.6

prompt; type_line 'gitui'
beat
pause 0.3
clear

printf '┌ Status ───────────────────────────────┬ Staged ───────────────────────────────┐\n'
printf '│ \033[38;5;81mM\033[0m internal/ui/readme.go            │ \033[38;5;120m+\033[0m reels/gum/demo.sh                │\n'
printf '│ \033[38;5;81mM\033[0m internal/catalog/index.json       │ \033[38;5;120m+\033[0m reels/bottom/demo.sh             │\n'
printf '│ \033[38;5;214m?\033[0m reels/gitui/demo.sh               │                                        │\n'
printf '│ \033[38;5;214m?\033[0m reels/yazi/demo.sh                │                                        │\n'
printf '│                                       │                                        │\n'
printf '└───────────────────────────────────────┴────────────────────────────────────────┘\n'
printf '┌ Diff ───────────────────────────────────────────────────────────────────────────┐\n'
printf '│ @@ -41,6 +41,9 @@ func renderReadme(...)                                       │\n'
printf '│ \033[38;5;120m+  // Try app reel above readme when available\033[0m                               │\n'
printf '│ \033[38;5;120m+  strip := newReelStripForApp(app.Slug, width)\033[0m                             │\n'
printf '│ \033[38;5;120m+  body = lipgloss.JoinVertical(lipgloss.Left, strip.View(), body)\033[0m         │\n'
printf '└─────────────────────────────────────────────────────────────────────────────────┘\n'
printf '┌ Commit ─────────────────────────────────────────────────────────────────────────┐\n'
printf '│ feat(reels): add first batch of autogenerated app demos                        │\n'
printf '└─────────────────────────────────────────────────────────────────────────────────┘\n'
printf '\033[2m  [TAB] switch panel   [s] stage   [u] unstage   [c] commit   [?] keybindings\033[0m\n'
pause 3.8

clear
