name = "apio"
description = ":seedling: Open source ecosystem for open FPGA boards"
author = "FPGAwars"
homepage = "https://github.com/FPGAwars/apio"
readme = "https://raw.githubusercontent.com/FPGAwars/apio/main/README.md"
tags = ["cli"]
category = "HTTP clients"
license = "GPL-3.0"

[[installs]]
type = "pipx"
package = "apio"
