name = "atmos"
description = "👽 Terraform Orchestration Tool for DevOps. Keep environment configuration DRY with hierarchical imports of configu..."
author = "cloudposse"
homepage = "https://github.com/cloudposse/atmos"
readme = "https://raw.githubusercontent.com/cloudposse/atmos/main/README.md"
tags = ["cli"]
license = "APACHE-2.0"

[[installs]]
type = "go"
package = "github.com/cloudposse/atmos@latest"
