name = "aws-nuke"
description = "Remove all the resources from an AWS account"
author = "ekristen"
homepage = "https://github.com/ekristen/aws-nuke"
readme = "https://raw.githubusercontent.com/ekristen/aws-nuke/main/README.md"
tags = ["cli"]
category = "DevOps"
license = "MIT"

[[installs]]
type = "go"
package = "github.com/ekristen/aws-nuke@latest"
