name = "boxen"
description = "Create boxes in the terminal"
author = "sindresorhus"
homepage = "https://github.com/sindresorhus/boxen"
readme = "https://raw.githubusercontent.com/sindresorhus/boxen/main/README.md"
tags = ["cli"]
category = "Shell utilities"
license = "MIT"

[[installs]]
type = "npm"
package = "boxen"
