name = "budget-tracker-tui"
description = "A simple TUI budget tracker app built in rust. Designed to track income and expenses and help visualize and gather ba..."
author = "Feromond"
homepage = "https://github.com/Feromond/budget_tracker_tui"
readme = "https://raw.githubusercontent.com/Feromond/budget_tracker_tui/main/README.md"
tags = ["cli"]
category = "Toys & visualizers"
license = "GPL-3.0"

[[installs]]
type = "cargo"
package = "budget_tracker_tui"
