name = "carapace-bin"
description = "A multi-shell completion binary."
author = "carapace-sh"
homepage = "https://github.com/carapace-sh/carapace-bin"
readme = "https://raw.githubusercontent.com/carapace-sh/carapace-bin/master/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "go"
package = "github.com/carapace-sh/carapace-bin@latest"
