name = "cargo-llvm-cov"
description = "Cargo subcommand to easily use LLVM source-based code coverage (-C instrument-coverage)."
author = "taiki-e"
homepage = "https://github.com/taiki-e/cargo-llvm-cov"
readme = "https://raw.githubusercontent.com/taiki-e/cargo-llvm-cov/main/README.md"
tags = ["cli"]
license = "APACHE-2.0"

[[installs]]
type = "cargo"
package = "cargo-llvm-cov"
