name = "cargo-msrv"
description = "🦀 Find the minimum supported Rust version (MSRV) for your project"
author = "foresterre"
homepage = "https://github.com/foresterre/cargo-msrv"
readme = "https://raw.githubusercontent.com/foresterre/cargo-msrv/main/README.md"
tags = ["cli"]
license = "APACHE-2.0"

[[installs]]
type = "cargo"
package = "cargo-msrv"
