name = "chepy"
description = "Chepy is a python lib/cli equivalent of the awesome CyberChef tool."
author = "securisec"
homepage = "https://github.com/securisec/chepy"
readme = "https://raw.githubusercontent.com/securisec/chepy/master/README.md"
tags = ["cli"]
category = "Other"
license = "GPL-3.0"

[[installs]]
type = "pipx"
package = "chepy"
