name = "cherrybomb"
description = "Stop half-done APIs! Cherrybomb is a CLI tool that helps you avoid undefined user behaviour by auditing your API spec..."
author = "blst-security"
homepage = "https://github.com/blst-security/cherrybomb"
readme = "https://raw.githubusercontent.com/blst-security/cherrybomb/main/README.md"
tags = ["cli"]
license = "APACHE-2.0"

[[installs]]
type = "cargo"
package = "cherrybomb"
