name = "cli-printing-press"
description = "Every API has a secret identity. This finds it, absorbs every feature from every competing tool, then builds the GOAT..."
author = "mvanhorn"
homepage = "https://github.com/mvanhorn/cli-printing-press"
readme = "https://raw.githubusercontent.com/mvanhorn/cli-printing-press/main/README.md"
tags = ["cli"]
category = "Security"
license = "MIT"

[[installs]]
type = "go"
package = "github.com/mvanhorn/cli-printing-press@latest"
