name = "cocogitto"
description = "The Conventional Commits toolbox"
author = "cocogitto"
homepage = "https://github.com/cocogitto/cocogitto"
readme = "https://raw.githubusercontent.com/cocogitto/cocogitto/main/README.md"
tags = ["cli"]
category = "Version control"
license = "MIT"

[[installs]]
type = "cargo"
package = "cocogitto"
