name = "code2prompt"
description = "A CLI tool to convert your codebase into a single LLM prompt with source tree, prompt templating, and token counting."
author = "mufeedvh"
homepage = "https://github.com/mufeedvh/code2prompt"
readme = "https://raw.githubusercontent.com/mufeedvh/code2prompt/main/README.md"
tags = ["cli"]
category = "AI tools"
license = "MIT"

[[installs]]
type = "cargo"
package = "code2prompt"
