name = "colorette"
description = "🌈Easily set your terminal text color & styles"
author = "jorgebucaran"
homepage = "https://github.com/jorgebucaran/colorette"
readme = "https://raw.githubusercontent.com/jorgebucaran/colorette/main/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "npm"
package = "colorette"
