name = "deploybot-cli"
description = "Deploybot terminal client"
author = "mrprompt"
homepage = "https://github.com/mrprompt/deploybot-cli"
readme = "https://raw.githubusercontent.com/mrprompt/deploybot-cli/master/README.md"
tags = ["cli"]
category = "DevOps"
license = "GPL-3.0"

[[installs]]
type = "pipx"
package = "deploybot-cli"
