name = "doit"
description = "CLI task management & automation tool"
author = "pydoit"
homepage = "https://github.com/pydoit/doit"
readme = "https://raw.githubusercontent.com/pydoit/doit/master/README.md"
tags = ["cli"]
category = "Productivity"
license = "MIT"

[[installs]]
type = "pipx"
package = "doit"
