name = "dstask"
description = "Git powered terminal-based todo/note manager -- markdown note page per task. Single binary!"
author = "naggie"
homepage = "https://github.com/naggie/dstask"
readme = "https://raw.githubusercontent.com/naggie/dstask/master/README.md"
tags = ["cli"]
category = "Productivity"
license = "MIT"

[[installs]]
type = "go"
package = "github.com/naggie/dstask@latest"
