name = "emqutiti"
description = "A polished MQTT terminal client"
author = "marang"
homepage = "https://github.com/marang/emqutiti"
readme = "https://raw.githubusercontent.com/marang/emqutiti/main/README.md"
tags = ["cli"]
category = "Shell utilities"
license = "MIT"

[[installs]]
type = "go"
package = "github.com/marang/emqutiti@latest"
