name = "f-license"
description = "Open Source License Key Generation and Verification Tool written in Go"
author = "furkansenharputlu"
homepage = "https://github.com/furkansenharputlu/f-license"
readme = "https://raw.githubusercontent.com/furkansenharputlu/f-license/master/README.md"
tags = ["cli"]
category = "Other"
license = "APACHE-2.0"

[[installs]]
type = "go"
package = "github.com/furkansenharputlu/f-license@latest"
