name = "gh-skyline"
description = "A GitHub CLI extension to generate a 3D model of your GitHub contribution history"
author = "github"
homepage = "https://github.com/github/gh-skyline"
readme = "https://raw.githubusercontent.com/github/gh-skyline/main/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "go"
package = "github.com/github/gh-skyline@latest"
