name = "git-delete-merged-branches"
description = ":fire: Command-line tool to delete merged Git branches"
author = "hartwork"
homepage = "https://github.com/hartwork/git-delete-merged-branches"
readme = "https://raw.githubusercontent.com/hartwork/git-delete-merged-branches/master/README.md"
tags = ["cli"]
category = "Version control"
license = "GPL-3.0"

[[installs]]
type = "pipx"
package = "git-delete-merged-branches"
