name = "gitmoji-cli"
description = "A gitmoji interactive cli tool for using emojis on commits. 💻"
author = "carloscuesta"
homepage = "https://github.com/carloscuesta/gitmoji-cli"
readme = "https://raw.githubusercontent.com/carloscuesta/gitmoji-cli/master/README.md"
tags = ["cli"]
category = "Version control"
license = "MIT"

[[installs]]
type = "npm"
package = "gitmoji-cli"
