name = "go-prompt"
description = "Building powerful interactive prompts in Go, inspired by python-prompt-toolkit."
author = "c-bata"
homepage = "https://github.com/c-bata/go-prompt"
readme = "https://raw.githubusercontent.com/c-bata/go-prompt/master/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "go"
package = "github.com/c-bata/go-prompt@latest"
