name = "gowall"
description = "A tool to convert a Wallpaper's color scheme / palette, OCR with VLM's Traditional & Hybrid, Image Compression ,color..."
author = "Achno"
homepage = "https://github.com/Achno/gowall"
readme = "https://raw.githubusercontent.com/Achno/gowall/main/README.md"
tags = ["cli"]
category = "Music & media"
license = "MIT"

[[installs]]
type = "go"
package = "github.com/Achno/gowall@latest"
