name = "haul"
description = "Haul is a command line tool for developing React Native apps, powered by Webpack"
author = "callstack"
homepage = "https://github.com/callstack/haul"
readme = "https://raw.githubusercontent.com/callstack/haul/master/README.md"
tags = ["cli"]
category = "Shell utilities"
license = "MIT"

[[installs]]
type = "npm"
package = "haul"
