name = "hostctl"
description = "Your dev tool to manage /etc/hosts like a pro!"
author = "guumaster"
homepage = "https://github.com/guumaster/hostctl"
readme = "https://raw.githubusercontent.com/guumaster/hostctl/master/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "go"
package = "github.com/guumaster/hostctl@latest"
