name = "hygen"
description = "The simple, fast, and scalable code generator that lives in your project."
author = "jondot"
homepage = "https://github.com/jondot/hygen"
readme = "https://raw.githubusercontent.com/jondot/hygen/master/README.md"
tags = ["cli"]
category = "Developer tools"
license = "MIT"

[[installs]]
type = "npm"
package = "hygen"
