name = "irccloud"
description = "Text-mode terminal client for IRCCloud"
author = "termoose"
homepage = "https://github.com/termoose/irccloud"
readme = "https://raw.githubusercontent.com/termoose/irccloud/master/README.md"
tags = ["cli"]
category = "DevOps"
license = "MIT"

[[installs]]
type = "go"
package = "github.com/termoose/irccloud@latest"
