name = "jid"
description = "json incremental digger"
author = "simeji"
homepage = "https://github.com/simeji/jid"
readme = "https://raw.githubusercontent.com/simeji/jid/master/README.md"
tags = ["cli"]
category = "Data tools"
license = "MIT"

[[installs]]
type = "go"
package = "github.com/simeji/jid@latest"
