name = "jplot"
description = "iTerm2 expvar/JSON monitoring tool"
author = "rs"
homepage = "https://github.com/rs/jplot"
readme = "https://raw.githubusercontent.com/rs/jplot/master/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "go"
package = "github.com/rs/jplot@latest"
