name = "jrnl"
description = "Collect your thoughts and notes without leaving the command line."
author = "jrnl-org"
homepage = "https://github.com/jrnl-org/jrnl"
readme = "https://raw.githubusercontent.com/jrnl-org/jrnl/develop/README.md"
tags = ["cli"]
license = "GPL-3.0"

[[installs]]
type = "pipx"
package = "jrnl"
