name = "json-repair"
description = "Repair malformed JSON from LLMs, APIs, logs, and user input in Python."
author = "mangiucugna"
homepage = "https://github.com/mangiucugna/json_repair"
readme = "https://raw.githubusercontent.com/mangiucugna/json_repair/main/README.md"
tags = ["cli"]
category = "AI tools"
license = "MIT"

[[installs]]
type = "pipx"
package = "json_repair"
