name = "kapp"
description = "kapp is a simple deployment tool focused on the concept of 'Kubernetes application' — a set of resources with the s..."
author = "carvel-dev"
homepage = "https://github.com/carvel-dev/kapp"
readme = "https://raw.githubusercontent.com/carvel-dev/kapp/develop/README.md"
tags = ["cli"]
category = "DevOps"
license = "APACHE-2.0"

[[installs]]
type = "go"
package = "github.com/carvel-dev/kapp@latest"
