name = "kino"
description = "A terminal client for browsing and playing Plex or Jellyfin media."
author = "mmcdole"
homepage = "https://github.com/mmcdole/kino"
readme = "https://raw.githubusercontent.com/mmcdole/kino/main/README.md"
tags = ["cli"]
category = "Music & media"
license = "MIT"

[[installs]]
type = "go"
package = "github.com/mmcdole/kino@latest"
