name = "landrun"
description = "Run any Linux process in a secure, unprivileged sandbox using Landlock. Think firejail, but lightweight, user-friendl..."
author = "Zouuup"
homepage = "https://github.com/Zouuup/landrun"
readme = "https://raw.githubusercontent.com/Zouuup/landrun/main/README.md"
tags = ["cli"]
category = "Monitoring"
license = "MIT"

[[installs]]
type = "go"
package = "github.com/Zouuup/landrun@latest"
