name = "layerx"
description = "Terminal-based Docker image layer inspector"
author = "deveshctl"
homepage = "https://github.com/deveshctl/layerx"
readme = "https://raw.githubusercontent.com/deveshctl/layerx/main/README.md"
tags = ["cli"]
category = "Music & media"
license = "MIT"

[[installs]]
type = "go"
package = "github.com/deveshctl/layerx@latest"
