name = "legit"
description = "Git for Humans, Inspired by GitHub for Mac™."
author = "frostming"
homepage = "https://github.com/frostming/legit"
readme = "https://raw.githubusercontent.com/frostming/legit/master/README.md"
tags = ["cli"]
category = "Version control"
license = "BSD-3-CLAUSE"

[[installs]]
type = "pipx"
package = "legit"
