name = "lla"
description = "blazing fast `ls` replacement with superpowers"
author = "chaqchase"
homepage = "https://github.com/chaqchase/lla"
readme = "https://raw.githubusercontent.com/chaqchase/lla/main/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "cargo"
package = "lla"
