name = "mangathr-legacy"
description = "A terminal client for downloading manga, with support for sites like MangaDex, Cubari and more."
author = "browningluke"
homepage = "https://github.com/browningluke/mangathr-legacy"
readme = "https://raw.githubusercontent.com/browningluke/mangathr-legacy/master/README.md"
tags = ["cli"]
category = "Networking"
license = "MIT"

[[installs]]
type = "npm"
package = "mangathr-legacy"
