name = "mdformat"
description = "CommonMark compliant Markdown formatter"
author = "hukkin"
homepage = "https://github.com/hukkin/mdformat"
readme = "https://raw.githubusercontent.com/hukkin/mdformat/master/README.md"
tags = ["cli"]
category = "Documentation"
license = "MIT"

[[installs]]
type = "pipx"
package = "mdformat"
