name = "mergestat-lite"
description = "Query git repositories with SQL. Generate reports, perform status checks, analyze codebases. 🔍 📊"
author = "mergestat"
homepage = "https://github.com/mergestat/mergestat-lite"
readme = "https://raw.githubusercontent.com/mergestat/mergestat-lite/main/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "go"
package = "github.com/mergestat/mergestat-lite@latest"
