name = "mnamer"
description = "media file renaming and organizing tool"
author = "jkwill87"
homepage = "https://github.com/jkwill87/mnamer"
readme = "https://raw.githubusercontent.com/jkwill87/mnamer/main/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "pipx"
package = "mnamer"
