name = "nanocl"
description = "Work in progress distributed system that simplifies the orchestration of containers and virtual machines."
author = "next-hat"
homepage = "https://github.com/next-hat/nanocl"
readme = "https://raw.githubusercontent.com/next-hat/nanocl/nightly/README.md"
tags = ["cli"]
license = "APACHE-2.0"

[[installs]]
type = "cargo"
package = "nanocl"
