name = "nba-go"
description = "🏀 💻 The finest NBA CLI."
author = "homerchen19"
homepage = "https://github.com/homerchen19/nba-go"
readme = "https://raw.githubusercontent.com/homerchen19/nba-go/master/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "npm"
package = "nba-go"
