name = "nexrender"
description = "📹 Data-driven render automation for After Effects"
author = "inlife"
homepage = "https://github.com/inlife/nexrender"
readme = "https://raw.githubusercontent.com/inlife/nexrender/master/README.md"
tags = ["cli"]
category = "Productivity"
license = "MIT"

[[installs]]
type = "npm"
package = "nexrender"
