name = "notebooklm-py"
description = "Unofficial Python API and agentic skill for Google Gemini Notebook. Full programmatic access to NotebookLM's features..."
author = "teng-lin"
homepage = "https://github.com/teng-lin/notebooklm-py"
readme = "https://raw.githubusercontent.com/teng-lin/notebooklm-py/main/README.md"
tags = ["cli"]
category = "AI tools"
license = "MIT"

[[installs]]
type = "pipx"
package = "notebooklm-py"
