name = "oauth2c"
description = "User-friendly OAuth2 CLI"
author = "SecureAuthCorp"
homepage = "https://github.com/SecureAuthCorp/oauth2c"
readme = "https://raw.githubusercontent.com/SecureAuthCorp/oauth2c/master/README.md"
tags = ["cli"]
category = "Security"
license = "APACHE-2.0"

[[installs]]
type = "go"
package = "github.com/SecureAuthCorp/oauth2c@latest"
