name = "oterm"
description = "the terminal client for LLMs"
author = "ggozad"
homepage = "https://github.com/ggozad/oterm"
readme = "https://raw.githubusercontent.com/ggozad/oterm/main/README.md"
tags = ["cli"]
category = "AI tools"
license = "MIT"

[[installs]]
type = "pipx"
package = "oterm"
