name = "pastel-vadimdemedes"
description = "🎨 Next.js-like framework for CLIs made with Ink"
author = "vadimdemedes"
homepage = "https://github.com/vadimdemedes/pastel"
readme = "https://raw.githubusercontent.com/vadimdemedes/pastel/main/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "npm"
package = "pastel"
