name = "pgschema"
description = "Terraform-style, declarative schema migration CLI for Postgres. Agent friendly."
author = "pgplex"
homepage = "https://github.com/pgplex/pgschema"
readme = "https://raw.githubusercontent.com/pgplex/pgschema/main/README.md"
tags = ["cli"]
license = "APACHE-2.0"

[install]
type = "go"
package = "github.com/pgplex/pgschema@latest"
