name = "pingme"
description = "PingMe - A unified CLI and web service for sending notifications across multiple messaging platforms"
author = "kha7iq"
homepage = "https://github.com/kha7iq/pingme"
readme = "https://raw.githubusercontent.com/kha7iq/pingme/master/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "go"
package = "github.com/kha7iq/pingme@latest"
