name = "pls"
description = "pls is a prettier and powerful ls(1) for the pros."
author = "pls-rs"
homepage = "https://github.com/pls-rs/pls"
readme = "https://raw.githubusercontent.com/pls-rs/pls/main/README.md"
tags = ["cli"]
category = "File management"
license = "GPL-3.0"

[[installs]]
type = "cargo"
package = "pls"
