name = "preevy"
description = "Quickly deploy preview environments to the cloud!"
author = "livecycle"
homepage = "https://github.com/livecycle/preevy"
readme = "https://raw.githubusercontent.com/livecycle/preevy/main/README.md"
tags = ["cli"]
category = "DevOps"
license = "APACHE-2.0"

[[installs]]
type = "npm"
package = "preevy"
