name = "promptr"
description = "Promptr is a CLI tool that applies plain language instructions to the filesystem. Instructions can utilize a liquidjs..."
author = "ferrislucas"
homepage = "https://github.com/ferrislucas/promptr"
readme = "https://raw.githubusercontent.com/ferrislucas/promptr/main/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "npm"
package = "promptr"
