name = "qnm"
description = ":mag: cli utility for querying the node_modules directory"
author = "ranyitz"
homepage = "https://github.com/ranyitz/qnm"
readme = "https://raw.githubusercontent.com/ranyitz/qnm/master/README.md"
tags = ["cli"]
category = "File management"
license = "MIT"

[[installs]]
type = "npm"
package = "qnm"
