name = "rasterio"
description = "Rasterio reads and writes geospatial raster datasets"
author = "rasterio"
homepage = "https://github.com/rasterio/rasterio"
readme = "https://raw.githubusercontent.com/rasterio/rasterio/main/README.md"
tags = ["cli"]
category = "Data tools"
license = "OTHER"

[[installs]]
type = "pipx"
package = "rasterio"
