name = "react-blessed"
description = "A react renderer for blessed."
author = "Yomguithereal"
homepage = "https://github.com/Yomguithereal/react-blessed"
readme = "https://raw.githubusercontent.com/Yomguithereal/react-blessed/master/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "npm"
package = "react-blessed"
