name = "restate"
description = "Restate is the platform for building resilient applications that tolerate all infrastructure faults w/o the need for..."
author = "restatedev"
homepage = "https://github.com/restatedev/restate"
readme = "https://raw.githubusercontent.com/restatedev/restate/main/README.md"
tags = ["cli"]
category = "HTTP clients"
license = "OTHER"

[[installs]]
type = "cargo"
package = "restate"
