name = "rich-click"
description = "Format click help output nicely with rich."
author = "ewels"
homepage = "https://github.com/ewels/rich-click"
readme = "https://raw.githubusercontent.com/ewels/rich-click/main/README.md"
tags = ["cli"]
category = "Developer tools"
license = "MIT"

[[installs]]
type = "pipx"
package = "rich-click"
