name = "sade"
description = "Smooth (CLI) Operator 🎶"
author = "lukeed"
homepage = "https://github.com/lukeed/sade"
readme = "https://raw.githubusercontent.com/lukeed/sade/master/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "npm"
package = "sade"
