name = "scraped"
description = "Scrape web pages in parallel, convert them to clean markdown, and navigate results using an interactive terminal brow..."
author = "Xhtira20"
homepage = "https://github.com/Xhtira20/scraped"
readme = "https://raw.githubusercontent.com/Xhtira20/scraped/main/README.md"
tags = ["cli"]
category = "Documentation"
license = "MIT"

[[installs]]
type = "go"
package = "github.com/Xhtira20/scraped@latest"
