name = "soft-serve"
description = "The mighty, self-hostable Git server with an SSH-accessible TUI"
author = "charmbracelet"
homepage = "https://github.com/charmbracelet/soft-serve"
readme = "https://raw.githubusercontent.com/charmbracelet/soft-serve/main/README.md"
tags = ["git", "ssh", "server", "tui"]
license = "MIT"
category = "Version control"
language = "Go"

[[installs]]
type = "brew"
package = "soft-serve"

[[installs]]
type = "go"
package = "github.com/charmbracelet/soft-serve/cmd/soft@latest"
