name = "spotify-cli"
description = "Terminal client for Spotify"
author = "jbszczepaniak"
homepage = "https://github.com/jbszczepaniak/spotify-cli"
readme = "https://raw.githubusercontent.com/jbszczepaniak/spotify-cli/master/README.md"
tags = ["cli"]
category = "Music & media"
license = "MIT"

[[installs]]
type = "go"
package = "github.com/jbszczepaniak/spotify-cli@latest"
