name = "sqlit"
description = "A user friendly TUI for SQL databases. Written in python. Supports SQL server, Mysql, PostreSQL, SQLite, Turso and more."
author = "Maxteabag"
homepage = "https://github.com/Maxteabag/sqlit"
readme = "https://raw.githubusercontent.com/Maxteabag/sqlit/main/README.md"
tags = ["cli"]
license = "MIT"

[install]
type = "pipx"
package = "sqlit"
