name = "srgn"
description = "A grep-like tool which understands source code syntax and allows for manipulation in addition to search"
author = "alexpovel"
homepage = "https://github.com/alexpovel/srgn"
readme = "https://raw.githubusercontent.com/alexpovel/srgn/main/README.md"
tags = ["cli"]
category = "Developer tools"
license = "MIT"

[[installs]]
type = "cargo"
package = "srgn"
