name = "table"
description = "Formats data into a string table."
author = "gajus"
homepage = "https://github.com/gajus/table"
readme = "https://raw.githubusercontent.com/gajus/table/master/README.md"
tags = ["cli"]
license = "OTHER"

[[installs]]
type = "npm"
package = "table"
