name = "term-everything"
description = "Run any GUI app in the terminal❗"
author = "mmulet"
homepage = "https://github.com/mmulet/term.everything"
readme = "https://raw.githubusercontent.com/mmulet/term.everything/main/README.md"
tags = ["cli"]
license = "AGPL-3.0"

[install]
type = "go"
package = "github.com/mmulet/term.everything@latest"
