name = "tmuxp"
description = "🖥️ Session manager for tmux, built on libtmux."
author = "tmux-python"
homepage = "https://github.com/tmux-python/tmuxp"
readme = "https://raw.githubusercontent.com/tmux-python/tmuxp/master/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "pipx"
package = "tmuxp"
