name = "tod0"
description = "A Terminal Client for Microsoft To-Do"
author = "kiblee"
homepage = "https://github.com/kiblee/tod0"
readme = "https://raw.githubusercontent.com/kiblee/tod0/master/README.md"
tags = ["cli"]
category = "Shell utilities"
license = "MIT"

[[installs]]
type = "pipx"
package = "tod0"
