name = "toon"
description = "🎒 Token-Oriented Object Notation (TOON) – compact, human-readable serialization of JSON data for LLM prompts. Ty..."
author = "toon-format"
homepage = "https://github.com/toon-format/toon"
readme = "https://raw.githubusercontent.com/toon-format/toon/main/README.md"
tags = ["cli"]
category = "AI tools"
license = "MIT"

[[installs]]
type = "npm"
package = "toon"
