name = "ttyd-client"
description = "A cross-platform terminal client for TTYD WebSocket connections"
author = "krypton-byte"
homepage = "https://github.com/krypton-byte/ttyd-client"
readme = "https://raw.githubusercontent.com/krypton-byte/ttyd-client/master/README.md"
tags = ["cli"]
category = "Shell utilities"

[[installs]]
type = "pipx"
package = "ttyd-client"
