name = "variety"
description = "Variety: a MongoDB schema analyzer"
author = "variety"
homepage = "https://github.com/variety/variety"
readme = "https://raw.githubusercontent.com/variety/variety/main/README.md"
tags = ["cli"]
category = "Databases"
license = "MIT"

[[installs]]
type = "npm"
package = "variety"
