name = "weather"
description = "Weather via the command line."
author = "genuinetools"
homepage = "https://github.com/genuinetools/weather"
readme = "https://raw.githubusercontent.com/genuinetools/weather/master/README.md"
tags = ["cli"]
category = "Shell utilities"
license = "MIT"

[[installs]]
type = "go"
package = "github.com/genuinetools/weather@latest"
