name = "what-anime-cli"
description = "❓🖼 Find the anime scene by image using your terminal"
author = "irevenko"
homepage = "https://github.com/irevenko/what-anime-cli"
readme = "https://raw.githubusercontent.com/irevenko/what-anime-cli/main/README.md"
tags = ["cli"]
license = "MIT"

[[installs]]
type = "go"
package = "github.com/irevenko/what-anime-cli@latest"
