name = "wisteria"
description = "Terminal Client for the Arbor Chat project, mirrored from sourcehut"
author = "arborchat"
homepage = "https://github.com/arborchat/wisteria"
readme = "https://raw.githubusercontent.com/arborchat/wisteria/master/README.md"
tags = ["cli"]
category = "Developer tools"
license = "APACHE-2.0"

[[installs]]
type = "go"
package = "github.com/arborchat/wisteria@latest"
