name = "wuzz"
description = "Interactive cli tool for HTTP inspection"
author = "asciimoo"
homepage = "https://github.com/asciimoo/wuzz"
readme = "https://raw.githubusercontent.com/asciimoo/wuzz/master/README.md"
tags = ["cli"]
license = "AGPL-3.0"

[[installs]]
type = "go"
package = "github.com/asciimoo/wuzz@latest"
