name = "yoda"
description = "Wise and powerful personal assistant, available in your nearest terminal"
author = "manparvesh"
homepage = "https://github.com/manparvesh/yoda"
readme = "https://raw.githubusercontent.com/manparvesh/yoda/v2/README.md"
tags = ["cli"]

[[installs]]
type = "pipx"
package = "yoda"
